inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1
  NewCops: disable
  SuggestExtensions: false

# https://github.com/SUSE/style-guides/blob/master/Ruby.md#strings
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

