FROM localhost/dbus-gui-ruby

RUN echo 'gem: --no-rdoc --no-ri' >> /.gemrc
RUN rbenv global 3.1.4
RUN git clone https://github.com/mvidner/dbus-gui-gtk.git
# don't collide on zypp locks
RUN cd dbus-gui-gtk; rbenv exec bundle install -j1
# ruby-gnome2.gem uses zypper to install dependencies. 200M of cache.
RUN zypper clean --all
